spring.application.name=LANChat

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=LAN

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kiruthikvairavel4906@gmail.com
spring.mail.password=uipefhnafssddfvg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Multipart uploads file size limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB