spring.application.name=LANChat

spring.mongodb.uri=mongodb+srv://727723euit106:kiruthik@democluster.87srj0r.mongodb.net/chatApplication

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kiruthikvairavel4906@gmail.com
spring.mail.password=uipefhnafssddfvg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Multipart uploads file size limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB